Marvell AC5x DB - Add single CPU Slim mode of operation
dentproject/dentOS pull request #164
Opened 2022-02-13 09:32 UTC by eladnachman

This Pull request and series of commits introduce a new Marvell switchdev mode of operation - the Slim mode of operation, which allows operating the switchdev on boards with only a single CPU.

Currently, this mode is supported for the Marvell AC5x SOC which combines switching Packet Processor and CPU on a single die, for the Marvell DB (Development Board).

2022-02-13 09:54 UTC, paulmenzel requested changes
1.  GitHub shows, that some files do not use UNIX line endings. It’d be great to have that fixed.
2.  The last commit should be squashed into the commit with the typo.

2022-02-13 09:54 UTC, paulmenzel commented on packages/platforms/marvell/arm64/ac5x-db/onlp/builds/arm64_marvell_ac5x_db/arm64_marvell_ac5x_db.mk
> +# Autogenerated 2022-02-08 15:37:45.681643
What command autogenerated these?

2022-02-13 13:19 UTC, eladnachman commented on packages/platforms/marvell/arm64/ac5x-db/onlp/builds/arm64_marvell_ac5x_db/arm64_marvell_ac5x_db.mk
> +# Autogenerated 2022-02-08 15:37:45.681643
Removed from Commit

2022-02-13 13:19 UTC, eladnachman commented
> 1. GitHub shows, that some files do not use UNIX line endings. It’d be great to have that fixed.
> 2. The last commit should be squashed into the commit with the typo.

Done

2022-02-13 13:38 UTC, taraschornyiplv submitted a review, later dismissed

2022-02-15 16:52 UTC, taraschornyiplv approved these changes

2022-02-20 16:25 UTC, robimarko commented
@taraschornyiplv Since you tagged me, can you explain how does this work?
I see that CPSS kmods are added for using DMA and interrupts from userspace.

2022-02-21 15:31 UTC, robimarko approved these changes

2022-02-21 15:56 UTC, taraschornyiplv approved these changes

2022-02-21 15:56 UTC, merged