prestera: Update prestera driver to v3.1.4
dentproject/dentOS pull request #172
Opened 2022-05-11 09:54 UTC by taraschornyiplv

Add debugfs support for setting IPG

To set IPG 
```bash
localhost# ls  /sys/kernel/debug/prestera/
hw_counters  ipg  sw_counters
localhost# cat  /sys/kernel/debug/prestera/ipg
ipg: 12
localhost# echo 4 >   /sys/kernel/debug/prestera/ipg
localhost# cat  /sys/kernel/debug/prestera/ipg
ipg: 4
localhost# echo 12 >   /sys/kernel/debug/prestera/ipg
localhost# cat  /sys/kernel/debug/prestera/ipg
ipg: 12
localhost# echo 13 >   /sys/kernel/debug/prestera/ipg
-bash: echo: write error: Invalid argument
localhost# cat  /sys/kernel/debug/prestera/ipg
ipg: 12
```
Signed-off-by: Taras Chornyi <taras.chornyi@plvision.eu>

2022-05-11 09:54 UTC, robimarko approved these changes

2022-05-11 10:02 UTC, paulmenzel requested changes
As I ask this every time, what is so hard to format the patch file with `git format-patch`?

2022-05-19 08:57 UTC, eladnachman approved these changes

2022-05-19 13:57 UTC, Mickey201 commented
@paulmenzel , This release is for a legacy stream based on automated CI/CD build procedures.
Future Switchdev releases (main/master based) are derived from the Linux REPO and can be easily addressed.

2022-05-19 14:06 UTC, paulmenzel commented
@Mickey201, sorry that is no argument. Please do the work adhering to current standards, and that is git formatted patches with a commit message explaining the changes.

2022-05-22 12:45 UTC, merged