Update iproute to v5.18
dentproject/dentOS pull request #181
Opened 2022-12-05 14:25 UTC by taraschornyiplv

Bump iproute2 package version to v5.18

2022-12-06 11:10 UTC, paulmenzel requested changes
1.  iprote → iproute in commit message summary.
2.  upsteram → upstream
3.  Please elaborate in [iprote2: Fix Makefile](https://github.com/dentproject/dentOS/pull/181/commits/69cb4225875a6d84a98d5a97480a3d21e1a2c918), what error you get, and why the commends before do not work anymore.
4.  Why not update to 6.0?

2022-12-06 11:10 UTC, paulmenzel commented on packages/base/any/iproute2/builds/Makefile
> +deps: deps-$(ARCH)
Please revert this file ending change.

2022-12-06 11:10 UTC, paulmenzel commented on packages/base/any/iproute2/builds/Makefile
> +	$(MAKE) V=1 PREFIX=/usr/local  HOSTCC=gcc -C iproute2
One space too much before `HOSTCC=`.

2022-12-06 14:16 UTC, taraschornyiplv commented on packages/base/any/iproute2/builds/Makefile
> +	$(MAKE) V=1 PREFIX=/usr/local  HOSTCC=gcc -C iproute2
done

2022-12-06 14:21 UTC, taraschornyiplv commented
> 1. iprote → iproute in commit message summary.
> 2. upsteram → upstream
> 3. Please elaborate in [iprote2: Fix Makefile](https://github.com/dentproject/dentOS/pull/181/commits/69cb4225875a6d84a98d5a97480a3d21e1a2c918), what error you get, and why the commends before do not work anymore.
> 4. Why not update to 6.0?

1. done
2. done
3. issue was with building iproute2 for amd64 platform also configure script does not check --host parameter
4. 5.18 is the first version to support locked flag.

2022-12-06 14:24 UTC, Mickey201 submitted a review, later dismissed

2022-12-06 14:54 UTC, paulmenzel commented
Thank you for amending the commits. Please add the explanations/clarifications to the commit messages.

> 1.  5.18 is the first version to support locked flag.

I’d still think, we should upgrade to [iproute2-6.0.0.tar.gz](https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/) right away.

2022-12-07 12:02 UTC, taraschornyiplv commented
> Thank you for amending the commits. Please add the explanations/clarifications to the commit messages.
> 
> > 1. 5.18 is the first version to support locked flag.
> 
> I’d still think, we should upgrade to [iproute2-6.0.0.tar.gz](https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/) right away.

let's integrate 5.18 first an 6.x once we move to a new stable kernel

2022-12-07 12:55 UTC, eladnachman approved these changes

2022-12-07 13:07 UTC, paulmenzel approved these changes

2022-12-07 15:56 UTC, merged