add poed deb package
dentproject/dentOS pull request #205
Opened 2023-03-03 06:01 UTC by muchetan

add poed debian package

2023-03-03 10:44 UTC, paulmenzel requested changes
Please amend the commit message and merge/pull request description, what the package contains, how much the image size grows, and maybe even give an example how to use it.

2023-03-06 19:35 UTC, muchetan commented
add poed deb package contains Power of Ethernet Driver and smbus2 driver
to talk to i2c, for more information https://github.com/dentproject/poed#readme
the package size ~30KB

2023-03-06 19:51 UTC, taraschornyiplv approved these changes

2023-03-07 10:29 UTC, paulmenzel commented
Thank you for your comment. It’ d be great, if you amended the commit message and merge/pull request description with that information.

2023-03-07 22:50 UTC, rothcar approved these changes

2023-03-08 04:08 UTC, merged